domain_path: C:\DevWorks_vitis\TankDuel\export\TankDuel\sw\freertos_ps7_cortexa9_1
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\freertos_lwip_echo_server
template: freertos_lwip_echo_server
lang: c
